[package]
name = "phenotype"
version = "0.6.0"
description = "C++ cross-platform UI framework with WebGPU renderer"
authors = ["misut"]
license = "MIT"
type = "lib"
standard = 23
platforms = [{ os = "wasi" }]

[dependencies]
