[package]
name = "phenotype"
version = "0.8.0"
description = "C++ cross-platform UI framework with WebGPU renderer"
authors = ["misut"]
license = "MIT"
type = "lib"
standard = 23
platforms = [
    { os = "wasi" },
    { os = "macos", arch = "aarch64" },
    { os = "linux", arch = "x86_64" },
]

[dependencies]
"github.com/misut/jsoncpp" = "0.1.3"
