[package]
name = "phenotype"
version = "0.16.0"
description = "C++ cross-platform UI framework"
authors = ["misut"]
license = "MIT"
type = "lib"
standard = 23
platforms = [
    { os = "wasi" },
    { os = "macos", arch = "aarch64" },
    { os = "windows", arch = "x86_64" },
]

[target.'cfg(os = "macos")'.build]
ldflags = ["-framework", "AppKit", "-Wl,-framework,CoreText"]

[sync]
cmake-in-root = false
