[package]
name = "hello"
version = "0.1.0"
description = "phenotype hello world example"
type = "bin"
standard = 23
platforms = [{ os = "wasi" }]

[dependencies]
"github.com/misut/cppx" = "1.6.1"

[dependencies.path]
phenotype = "../.."
