[package]
name = "counter"
version = "0.1.0"
description = "phenotype counter example with reactive state"
type = "bin"
standard = 23
platforms = [{ os = "wasi" }]

[dependencies]
"github.com/misut/cppx" = "1.6.3"

[dependencies.path]
phenotype = "../.."
