#!/usr/bin/env sh
# Offline-compile phenotype's Android GLSL shaders to SPIR-V and emit
# a C++ header of uint32_t blobs that phenotype.native.android.cppm
# includes.
#
# phenotype's Android backend mirrors the desktop pattern of keeping
# shader code in-source, but Vulkan drivers only accept SPIR-V, so we
# precompile here and commit the resulting .inl. Rerun this script
# whenever a .vert / .frag under src/phenotype.native.android.shaders
# changes.
#
# Usage:
#   ANDROID_NDK_HOME=/path/to/android-ndk-r30+ ./tools/compile_android_shaders.sh
set -eu

: "${ANDROID_NDK_HOME:?ANDROID_NDK_HOME must point at an NDK r30+ install}"

case "$(uname -s)" in
    Darwin) HOST=darwin-x86_64 ;;
    Linux)  HOST=linux-x86_64  ;;
    *) echo "unsupported host: $(uname -s)" >&2; exit 1 ;;
esac

GLSLC="$ANDROID_NDK_HOME/shader-tools/$HOST/glslc"
[ -x "$GLSLC" ] || {
    echo "glslc not found at $GLSLC — check ANDROID_NDK_HOME" >&2
    exit 1
}

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/src/phenotype.native.android.shaders"
OUT="$ROOT/src/phenotype.native.android.shaders.inl"

emit_blob() {
    name=$1; stage=$2; source=$3
    tmp="$(mktemp)"
    "$GLSLC" --target-env=vulkan1.1 -mfmt=num -O \
        "-fshader-stage=$stage" -o "$tmp" "$source"
    printf '// Auto-generated from %s. Do not edit.\n' \
        "$(basename "$source")"
    printf 'inline constexpr uint32_t %s[] = {\n' "$name"
    cat "$tmp"
    printf '};\n\n'
    rm -f "$tmp"
}

{
    printf '// Regenerated by tools/compile_android_shaders.sh.\n'
    printf '// Do not edit by hand — re-run the script when the .vert / .frag\n'
    printf '// sources under src/phenotype.native.android.shaders change.\n'
    printf '//\n'
    printf '// glslc version:\n'
    "$GLSLC" --version | sed 's|^|//   |'
    printf '\n'
    emit_blob SPIRV_COLOR_VS vertex   "$SRC/color.vert"
    emit_blob SPIRV_COLOR_FS fragment "$SRC/color.frag"
    emit_blob SPIRV_ARC_VS   vertex   "$SRC/arc.vert"
    emit_blob SPIRV_ARC_FS   fragment "$SRC/arc.frag"
    emit_blob SPIRV_TEXT_VS  vertex   "$SRC/text.vert"
    emit_blob SPIRV_TEXT_FS  fragment "$SRC/text.frag"
    emit_blob SPIRV_IMAGE_VS vertex   "$SRC/image.vert"
    emit_blob SPIRV_IMAGE_FS fragment "$SRC/image.frag"
} > "$OUT"

echo "wrote $OUT"
