[package]
name = "docs"
version = "0.1.0"
description = "phenotype documentation site"
type = "bin"
standard = 23
platforms = [{ os = "wasi" }]

[dependencies]
"github.com/misut/cppx" = "1.6.2"

[dependencies.path]
phenotype = ".."

[sync]
cmake-in-root = false
