[package]
name = "files-macos"
version = "0.1.0"
description = "macOS native Files example for phenotype"
authors = ["misut"]
license = "MIT"
type = "bin"
standard = 23
platforms = [{ os = "macos", arch = "aarch64" }]

[dependencies]

[dependencies.workspace]
phenotype-core = true

[dependencies.path]
phenotype-macos = "../../../macos"

[sync]
cmake-in-root = false
